baseurl = ""

[Params]
    mainSections = ["post"]
    intro = true
    headline = "My headline"
    description = "I'm a Full-stack Developer based in Paris, welcome to my digital world"
    github = "https://github.com/ermos"
    twitter = "https://twitter.com/doplex_"
    email = "kilian.smiti@outlook.fr"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[params.Codepen]
  user = "kevingimbel"
  editable = true
  preview = true
  script_src = "/codepen.js"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

[menu]
  [[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    identifier = "blog"
    url = "/post/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[Permalinks]
    post = "/post/:filename/"

[taxonomies]
  category = "category"
  tag = "tags"
  series = "series"