baseurl = "/"
title = "My blog"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "My headline"
    description = "My description"
    github = "https://github.com/ermos"
    twitter = "https://twitter.com/doplex_"
    email = "kilian.smiti@outlook.fr"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"

[taxonomies]
  category = "category"
  tag = "tags"
  series = "series"